### ISSUE TITLE
Program has exited with code 1

### ISSUE THREAD

**Issue by andhicak** [andrewssobral/simple_vehicle_counting#11]
Please help,  I'm using VS2013. But, the program always exited when I run the project. What should I do? 
![error](https://cloud.githubusercontent.com/assets/18673951/16034323/5acb2c30-323b-11e6-951d-f7ba9c9f9f9d.PNG)

**Comment by andrewssobral** [comment]
Hi @andhicak , Sorry for my very late response. You need only to copy the ***.exe** file from your building directory (e.g. simple_vehicle_counting/build/Debug/etc) and paste in the root folder **simple_vehicle_counting/**. Best
