### ISSUE TITLE
the version of opencv

### ISSUE THREAD

**Issue by sophia44** [andrewssobral/simple_vehicle_counting#17]
Hi Andrews, I notice that you said the project can use OpenCV 2.4.x (it only works with this version).I run your code, it runs successful, but it couldn't load the video.avi, I try some methods to solve this problem but they all failed. I‘d like to ask if its gonna possible because I use the version of  opencv is 2.4.9 rather than 2.4.10. Thank you so much~

**Comment by andrewssobral** [comment]
Hi @sophia44 you are on Windows? If yes, I think the problem is that you need to put the OpenCV bin path in your system path or by copying the ffmpeg DLL from your opencv bin into the working directory (where your *.exe is located). Please let me know if it works for you...
Best

**Comment by sophia44** [comment]
@andrewssobral Hi Andrews, thank you so much for answering my question, yes I am on windows. In fact, I have already put the OpenCV bin path in my system path. Another advice you said copying the ffmpeg DLL from my opencv bin into the working directory (where your *.exe is located), dose it means I should copy them to SYSTEM32 or SYSWOW？ If so, than I have already try them but I still couldn't load the video.avi. I used to use my computer to build camshift or codebook project they all succeed, so I think the basic environment of my vs2013 and opencv might be right.

**Comment by sophia44** [comment]
I changed the opencv2.4.9 to 2.4.10 and finally did it ,thank you very much!

**Comment by andrewssobral** [comment]
Nice! happy to see that it worked for you,
Best
