### ISSUE TITLE
Video Playback time very slow

### ISSUE THREAD

**Issue by aubryll** [andrewssobral/simple_vehicle_counting#4]
sorry about this but I do not know whether or not my Computer is absolute but you sample really lags, I do not think its my computer, I was doing a background subtractor app in Java with frame size of 700 + 600 and was working perfect with no lag but this sample lags uncontrollably, is there something am missing out that I have not yet discovered?

**Comment by andrewssobral** [comment]
Hi @aubryll do you have compiled the source code in release or debug mode?

**Comment by aubryll** [comment]
I was in debug mode, just a general question, is there a better way of increasing performance apart from integrating the GPU?

**Comment by andrewssobral** [comment]
Hi @aubryll , compile and run the source code in release mode, you will see a better performance.
Usually this source code is simple and fast, how many FPS are you getting?

**Comment by aubryll** [comment]
Andrew I am getting around 5fps, its not your program that is not ok, its my computer, I was using a very old computer.
