### ISSUE TITLE
just can't open the video

### ISSUE THREAD

**Issue by rakhaagung16** [andrewssobral/simple_vehicle_counting#5]
Hi, thank you for response my question on https://www.youtube.com/watch?v=27JxVkpIXW0 ..
I can't opened the video from your project file. When I debug your program, the 'black box' will showed and just closed but I've read the message from the black box. the message is, 'cannot open the video'.. Black box I mean, a box with black color. please give me a solution, thank you so much, Sir.

**Comment by andrewssobral** [comment]
Hi @rakhaagung16 this is a strange error, are you sure to have the appropriate video codecs? you may need to check your opencv compilation flags and related codecs, are you using a linux-based OS? (ubuntu,debian,etc.)
This is a great tutorial to How to install OpenCV 3.1 for Python on Ubuntu 14.04
http://www.askaswiss.com/2016/01/how-to-install-opencv-3-1-python-ubuntu-14-04.html

**Comment by rakhaagung16** [comment]
no, I am used windows 8.1.. Please tell me how to fix my problem.
visual studio 2013 and by the way how to check the appropriate video codecs?
can I get your phone number? so I can contact you by whatsapps. Thank you so much, Sir.

**Comment by andrewssobral** [comment]
Hi @rakhaagung16 you can try to install the K-Lite Codec Pack Full available here:
http://www.codecguide.com/download_k-lite_codec_pack_full.htm
And check if the OpenCV binaries are in your windows path (especially opencv_ffmpeg.dll).
