### ISSUE TITLE
How to detect motorcycle

### ISSUE THREAD

**Issue by teddyernanto** [andrewssobral/simple_vehicle_counting#6]
Hello, Mr. Andrew. I'm Teddy Ernanto. I ask where is the code must changed for detect motorcycle? Change minArea & maxArea or any else?

**Comment by andrewssobral** [comment]
Hello @teddyernanto yes, you can adapt the souce code for other object types. For motorcycle you may need to change the minArea and maxArea. If it does not works very well, you may need to change the background subtraction algorithm and/or apply some morphological operator algorithms to enhance the foreground mask.

**Comment by teddyernanto** [comment]
Sorry,I just read your reply,Mr. Andrew
Yes, I reduce minArea and maxArea value. Now, I can detect many
motorcycles. But, any motorcycle does not detect. I try to update this value

cvb::cvUpdateTracks(blobs, tracks, 100., 10);

Am I wrong?

This is my BlobTracking.xml

<?xml version="1.0"?>
<opencv_storage>
<minArea>600</minArea>
<maxArea>1200</maxArea>
<debugTrack>0</debugTrack>
<debugBlob>0</debugBlob>
<showBlobMask>0</showBlobMask>
<showOutput>1</showOutput>
</opencv_storage>

Thanks a lot for your explanation, Mr Andrew
