### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by Tes3awy** [andrewssobral/simple_vehicle_counting#7]
Do you have any idea how to make a Python Code instead of using C. I am not a big fan of Microsoft Languages :smile: . Help would be really appreciated, detection is easy to do, but my problem is in counting

**Comment by andrewssobral** [comment]
Hi @Tes3awy unfortunately the source code is available only in standard C++ language, you can compile it in Windows, Linux and Mac OS. Only the template project is based on Microsoft Visual Studio application.
