### ISSUE TITLE
Slow Action when it works in OS Linux Ubuntu Odroid

### ISSUE THREAD

**Issue by teddyernanto** [andrewssobral/simple_vehicle_counting#9]
Hello, Mr. Andrew. I'm Teddy Ernanto. Before I ask about how to detect motorcycle and it works in VS2013 Windows. Now, I use odroid with OS Linux Ubuntu 14.04 and OpenCV 2.4.12. The system works is too slow when detect from camera. 

1. Can I change PBAS with other algorithm? Example FrameDifferentTest.cpp in your sub folder BGS Library
2. Any changes for Cmake?

**Comment by andrewssobral** [comment]
Hi @teddyernanto 
I am sorry for my long delayed response.
Yes you can replace the PBAS algorithm for which you want.
No changes in CMake file if you are using the package_bgs from bgslibrary.
Best,
Andrews
